### ISSUE TITLE
Do we still need the "app" folder?

### ISSUE THREAD

**Issue by decentral1se** [biobulkbende/biobulkbende.org#2]
@Tancre I see that the `npm run start` command does `serve -l tcp://0.0.0.0:5000 docs` and I am wondering if we still need [the app](https://github.com/biobulkbende/biobulkbende.org/tree/main/app) folder? There is a lot of stuff in [the gulpfile](https://github.com/biobulkbende/biobulkbende.org/blob/main/gulpfile.js) referencing it, so I am not sure. I am raising because it is a bit confusing which `index.html` to edit?

**Comment by Tancre** [comment]
Hei luke. Yes DONT delete the app folder, I'm actually developing from
there. Because initially I was serving it from git pages there is a docs
folder + I added the English version there manually.
I'll make some changes and make clear which index.html to edit asap.

**Comment by Tancre** [comment]
For now if you need to change something do it in the docs and remember to
change also the english version. A day of next week I'm going to remove the
docs folder and we can deploy directly from app but I'll let you know when
so we can change the autodeploy in the same moemnt.

Il giorno sab 22 mag 2021 alle ore 13:20 tan digio ***@***.***>
ha scritto:
